title: Mathav Krishnan
description: Embedded Software Developer | Vehicle Control Systems | IoT and Real-Time Systems
author:
  name: Mathav Krishnan
  email: s.mathavkrishnan@gmail.com
  github: mathavkrishnan
  linkedin: mathav-krishnan-a67806219
url: https://Mathavk1606.github.io
baseurl: ""
social:
  - title: github
    url: https://github.com/mathavkrishnan
  - title: linkedin
    url: https://www.linkedin.com/in/mathav-krishnan-a67806219/
  - title: email
    url: mailto:s.mathavkrishnan@gmail.com